### ISSUE TITLE
Cannot read property 'prototype' of undefined / missing TextDecoder.

### ISSUE THREAD

**Issue by hollanderbart** [hollanderbart/BusinessCards-Connect#1]
When trying to run this example app, the app will not work because it's missing the function for `TextDecoder`. If I would integrate a polyfill for it, the error is gone. The TextDecoder is added to expo nowadays, so what is wrong with this project?

<img src="https://github.com/user-attachments/assets/d39e0947-7b9f-4201-b082-6ece27aac087" width="400" />

### Steps to reproduce:
Run the app as described in the Readme.

1. Clone the repository
2. Run `npm ci`
3. Run `npx pod-install` to install the pods
4. Open Xcode and run the project or run `npm run ios` to run the project on the
   simulator from the command line.
5. Use the app on the simulator

**Comment by hollanderbart** [comment]
@smaye81 I've created the project issue here, so we can continue the conversation here. Thanks for all the help until now.

**Comment by smaye81** [comment]
I took a quick look and was able to recreate the issue. However, I'm not entirely sure what's going on. I suspect this has something to do with Metro's bundling, but I can't say for sure. I noticed though that you're not using Expo at all even though it's installed? I would recommend maybe copying our exact example and then simply changing some of the .tsx files. That or maybe try using `npx create-expo-app <your app name>` and then copying your files into that directory.

React-Native isn't the most intuitive sometimes, so it's a bit hard to tell with these various moving parts.

**Comment by hollanderbart** [comment]
Yeah I think you're right. I like to keep the application as slim as possible and not rely on Expo too much. Now it seems that I need to rely on expo's virtual metro entry, so using the main entry in the package.json.
Thanks for your support.
